-- Migration 026: Add visibility_queries column to cluster_strategy
-- Stores AI visibility measurement queries generated by Section 7 of cluster strategy prompt
ALTER TABLE public.cluster_strategy ADD COLUMN IF NOT EXISTS visibility_queries JSONB;
